pipeline {

	agent any

	stages {

		stage("build") {

			steps {
				echo 'build stage'
				echo "Current build ID is: ${env.BUILD_ID}"
				echo "Current build number is: ${env.BUILD_NUMBER}"
		

			}

		}

		stage("test") {
			
			//when {
			//	expression {
			//		${env.BRANCH_NAME} == 'dev'
			//	}
			}
                        steps {
				echo "BRANCH name is ${env.BRANCH_NAME}"
				echo "test stage - only execute this if 'dev' branch"
                        }

                }

		stage("deploy") {

                        steps {
				echo 'deploy stage'
                        }

                }

	}

}
