pipeline {

        agent any

        stages {

                stage("build") {

                        steps {
                                echo 'build stage'
                                echo "Current build ID is: ${env.BUILD_ID}"
                                echo "Current build number is: ${env.BUILD_NUMBER}"

                        }

                }

                stage("test") {
                        when {
                                expression {
                                        ${env.BRANCH_NAME} == 'dev'
                                }
                        }
                        steps {
                                echo "test stage - This stage only get executed if 'dev' branch"
                        }

                }

                stage("deploy") {

                        steps {
                                echo 'deploy stage'
                        }

                }

        }

}
