pipeline {

	agent any

	stages {

		stage("build") {

			steps {
				echo 'build stage'
				echo "Current build ID is: ${env.BUILD_ID}"
				echo "Current build number is: ${env.BUILD_NUMBER}"
		

			}

		}

		stage("test") {

                        steps {
				echo "test stage"
                        }

                }

		stage("deploy") {

                        steps {
				echo 'deploy stage'
                        }

                }

	}

}
